# MySQL. Versions 5.0 and up are supported.
#
# Install the MySQL driver:
#   gem install activerecord-jdbcmysql-adapter
#
# Configure Using Gemfile
# gem 'activerecord-jdbcmysql-adapter'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.7/en/old-client.html
#

<% db_name = ENV['DB_NAME'] || 'fcms'  %>
<% db_host = ENV['DB_HOST'] || 'localhost' %>
<% db_user = ENV['DB_USER'] || 'root' %>
<% db_pass = ENV['DB_PASS'] || '' %>
<% db_pool = ENV['DB_POOL'] || 5 %>
<% db_url  = ENV['DB_URL'] %>

<% $stderr.puts "Using DB URL: #{db_url}" %>

default: &default
  adapter: mysql
  <% if ENV['DB_URL'] %>
    url: "jdbc:mysql://u8ze3v8fpfqmz1n8:gx7wuek4keopqt8o@d5x4ae6ze2og6sjo.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/wpsgt5qmhwon0yc3"
  <% else %>
    username: <%= db_user %>
    password: <%= db_pass %>
    host: <%= db_host %>
    pool: <%= db_pool %>
  <% end %>

development:
  <<: *default
  database: <%= db_name %>

test:
  <<: *default
  database: <%= db_name %>_test

production:
  <<: *default
  pool: 40